### PR TITLE
Add support for Ruby & Elixir from asdf version manager

### PR DESCRIPTION
**Pull request by Cervajz**
asdf is yet another version manager, similar to rbenv or rvm. The main difference is that it supports multiple languages through plugins

https://github.com/asdf-vm/asdf

image

### CODE REVIEW

**Comment by victorbrender** [comment]
👍

**Comment by Cervajz** [comment]
@scorphus I can extend all currently supported languages (node, python, rust) with asdf query as part of this PR as well. Let me know :)

**Comment by NetCZ** [comment]
👍

**Comment by scorphus** [comment]
I didn't know asdf. Nice tool, @Cervajz! It's a great idea to add support to it.

I've been doing small changes to the theme. You can take a look in the [experiments](https://github.com/oh-my-fish/theme-scorphish/tree/experiments) branch.

Please let me know what you think!

Also, it would be nice if you could rebase your work on top of that

**Comment by scorphus** [comment]
> […] I've been doing small changes to the theme. […] Please let me know what you think! […]

I've created #9 so we can discuss it there.

**Comment by Cervajz** [comment]
@scorphus No problem. I am going to rebase my branch and extend the asdf support for other languages that this theme already support.

I am also going to extract Elixir support from the asdf as those are separate matters.

**Pull request closed without merging**
