### PR TITLE
Reorganize left and right prompt

### PR DESCRIPTION
**Pull request by scorphus**
**Do not merge yet**, still a work in progress. Feedbacks are more than welcome.

### CODE REVIEW

**Comment by scorphus** [comment]
@pedrosnk there's also this PR where we can discuss the changes! Your inputs are more than welcome 🙂

**Comment by pedrosnk** [comment]
I've been using this branch for the last couple o days and I'm loving it.
I believe that it's stable enough to consider the merge

**Comment by scorphus** [comment]
Hey, @pedrosnk, I've added a few improvements regarding speed, cache invalidation, configuration and a new feature that shows the execution time for the last command. Would you be so kind to test it and give me your thoughts? Thanks in advance.

@oh-my-fish/core I'd be very happy if any of you would also share your opinion and/or review the changes.

**Comment by scorphus** [comment]
I'll go ahead and merge this PR as the theme has a few issues. If it accidentally breaks something, please file a new issue and I'll be happy to fix.

**Pull request merged**
